### ISSUE TITLE
Bugs not associated with databases I found in basicInfo module

### ISSUE THREAD

**Issue by blackhatdwh** [nslam/jwsys#2]
# 黑盒测试
### 主界面
- 登录状态不会保留，也就登陆后在任何界面在浏览器地址栏输入http://127.0.0.1:8000/basicInfo/ 就需要重新登录
- 进入分界面后无法返回主界面，改地址需要重新登录，点浏览器返回则浏览器报错Confirm Form Resubmission
- 登陆后在主界面刷新一次就会报403的错
### 修改密码
- 初始密码为password。通过正确的步骤将密码修改为password1。提示修改成功，并返回修改密码界面。此时在原密码处输入password1，两个新密码随便输，一样不一样都行，点确定就会404
### 个人信息
- 住址不支持中文
- 电话号码可以修改为字母，如“abc”
- 电话号码过长会出现错误，过短则不会。如修改为“1234567891234567”会报错，但允许修改为“123”
- 点击修改，跳出修改成功提示后页面就变成空白，需要点浏览器返回按钮才能回到修改页面

### 个人信息
- N/A
### 成绩查询
- 左上角欢迎处没有学生学号

### 登录页面
- 作为教师登录错误的话，alert的是you are not a instructor！a或为an
### Else
- N/A

### 登录页面
- 作为管理员登录的话，如果输入一个不存在的管理员账号，alert的也是password incorrect，而非you are not a manager
- 在管理员登录处输入存在的学生/教师的账号密码，可以进入管理员界面
### 查询修改课程信息
- 左上角欢迎处没有admin
- 输入存在的课程号点击查询，却查不到（课程是在MySQL中手动向basicInfo_course中添加的）
### 删除课程
- 左上角欢迎处没有admin
- 输入存在的课程号点击查询，却查不到（课程是在MySQL中手动向basicInfo_course中添加的）
### 用户添加
- N/A
### 用户信息查询修改
- 左上角没有欢迎
- 输入存在的用户点击查询，却查不到（用户通过python3 manage.py createStudent添加）
### 删除用户
- 左上角欢迎处没有admin
- 输入存在的用户点击搜索，却查不到（用户通过python3 manage.py createStudent添加）

**Comment by keys961** [comment]
BUG已经消除 
用户友好性 就不要管了
