### ISSUE TITLE
Bugs associated with databases I found in basicInfo module

### ISSUE THREAD

**Issue by blackhatdwh** [nslam/jwsys#3]
# 黑盒测试
### 个人信息
- 不显示姓名，可能是我没有找到数据库里对应的表。
- 修改后返回空白页面
### 成绩查询
- 绩点没有四舍五入，如80分的绩点为3.5999999999999996
- 本专业排名不可用
- 毕业要求总学分不可用

### 个人信息
- 不显示姓名，专业和学院，可能是我没有找到数据库里对应的表。
- 修改后返回空白页面
### 添加课程
- 课程号无法自动生成
- 上一条导致只能添加一门课程，否则会因为课程号都是none而被数据库拒绝。
- 从此处添加课程，并不会建立该教师与该课程的联系，即courseArrange_teaches中没有新建记录。这导致教师在“查看课程”中并不能看到自己开的课。
- 修改后返回空白页面
### 查看课程
- 通过在数据库中手工插入的方式插入课程，则在“查看课程”中各项都显示为模板而非真实值，即{i.courseNumber}	{i.title}	{i.credit}	{i.weekHour}	{i.method}
### 成绩录入
- 不可用
### 成绩查询
- 只能显示课程列表，无实际作用
- 该列表第一列为“开课信息”，或为“开课号”
### 成绩修改
- 只能显示课程列表，无实际作用
- 该列表第一列不显示

### 个人信息
- 不显示姓名，可能是我没有找到数据库里对应的表。
- 修改后返回空白页面
### 修改课程
- 修改课程号的逻辑有误。设现有两课程，第一门课程号为1001，第二门课程号为1002。查询课程1001，将其课程号修改为1002。这样产生的结果是，第一门课程未发生变化，第二门课程除了课程号，别的信息都变成和第一门课程一样的了。并且，也无法将某门课的课程号修改为一个现在并不存在的课程号。如上面的例子中，无法讲第一门课程的课程号修改为1003。
- 修改后返回空白页面
### 删除课程
- 删除中的查询可用，删除按钮不可用
### 添加用户
- 略过
### 查询修改用户
- 查询正常，但修改用户信息并提交后，报403的错，CSRF verification failed.
### 删除用户
- 查询正常，但删除不可用。

**Comment by kkriscc** [comment]
那位说查询修改用户那里有错的老哥，那个是表单提交被拦截了。我也遇到了。解决方法是去setting.py里面把MIDDLEWARE下的有一行csrf的给注释掉。

**Comment by blackhatdwh** [comment]
强！

**Comment by keys961** [comment]
姓名不显示（的确你没有加信息）
空白页面，就留空白吧
老师： 
1.课程号无法自动生成（是有问题= =）(现已解决）
2.添加课程只是往course表里加东西，而教师查询课程要和排课联系在一起的，所以当然不会显示（你需要在section里添加信息）
3. 成绩查询/修改可能有问题，到时候改
4. 查看课程不会显示原始模板字段的，请检查你的代码是否最新
管理员：
1. 课程号是不让修改的
2. 在我这里，删除和修改功能是一切正常的
